local assert = require('util/test')
local fu = require('util/func')

describe('func', function()
  describe('identity', function()
    it('normal', function()
      local obj = {}
      assert.are.equal(obj, fu.identity(obj))
      assert.are.not_equal({}, fu.identity(obj))
    end)
  end)

  describe('is_truthy', function()
    it('normal', function()
      assert.are.equal(true, fu.is_truthy({}))
      assert.are.equal(true, fu.is_truthy(1))
      assert.are.equal(true, fu.is_truthy(0))
      assert.are.equal(true, fu.is_truthy('a'))
      assert.are.equal(true, fu.is_truthy(''))
      assert.are.equal(true, fu.is_truthy(true))
      assert.are.equal(false, fu.is_truthy(false))
      assert.are.equal(false, fu.is_truthy(nil))
    end)
  end)

  describe('negate', function()
    it('normal', function()
      assert.are.equal(true, fu.negate(fu.is_truthy)(false))
    end)
  end)
end)
